name: muonroi
description: muonroi
publish_to: 'none'
version: 1.0.5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.13.1
  dio: ^5.3.2
  draggable_expandable_fab: ^1.0.0
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  extended_image: ^8.1.0
  firebase_auth: ^4.14.0
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress: ^2.0.4
  flutter_local_notifications: ^15.1.1
  flutter_logs: ^2.1.10
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  google_mobile_ads: ^3.1.0
  google_sign_in: ^6.1.6
  html: ^0.15.4
  http: ^1.1.0
  http_parser: ^4.0.2
  icons_flutter: ^0.0.4
  image: ^4.1.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  logging: ^1.2.0
  mailto: ^2.0.0
  mime: ^1.0.4
  path: ^1.8.3
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.0
  signalr_netcore:
    git:
      url: https://github.com/geekz-reno/signalr_client.git
      ref: master  
  sprintf: ^7.0.0
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.2.1
  uuid: ^3.0.7
  firebase_core: ^2.22.0
  battery_info: ^1.1.1
  encrypt: ^5.0.3
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.3
  package_info_plus: ^4.2.0
  internet_connection_checker: ^1.0.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launch.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/fonts/
    - assets/fonts/Inters/
    - assets/fonts/Poppins/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inters/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inters/Inter-Regular.ttf
          style: italic
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          style: italic
          weight: 500